package com.jwebcoder.emailsystem.entity;

public class ContentTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.ORDER_NUM
     *
     * @mbg.generated
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.OWNER
     *
     * @mbg.generated
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.CREATE_DATETIME
     *
     * @mbg.generated
     */
    private String createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.LAST_UPDATE_DATETIME
     *
     * @mbg.generated
     */
    private String lastUpdateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.CUSTOM1
     *
     * @mbg.generated
     */
    private String custom1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.CUSTOM2
     *
     * @mbg.generated
     */
    private String custom2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.CUSTOM3
     *
     * @mbg.generated
     */
    private String custom3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.CUSTOM4
     *
     * @mbg.generated
     */
    private Integer custom4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.CUSTOM5
     *
     * @mbg.generated
     */
    private Integer custom5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTENT_TEMPLATE.TEMPLATE
     *
     * @mbg.generated
     */
    private byte[] template;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.ID
     *
     * @return the value of CONTENT_TEMPLATE.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.ID
     *
     * @param id the value for CONTENT_TEMPLATE.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.VERSION
     *
     * @return the value of CONTENT_TEMPLATE.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.VERSION
     *
     * @param version the value for CONTENT_TEMPLATE.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.ORDER_NUM
     *
     * @return the value of CONTENT_TEMPLATE.ORDER_NUM
     *
     * @mbg.generated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.ORDER_NUM
     *
     * @param orderNum the value for CONTENT_TEMPLATE.ORDER_NUM
     *
     * @mbg.generated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.OWNER
     *
     * @return the value of CONTENT_TEMPLATE.OWNER
     *
     * @mbg.generated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.OWNER
     *
     * @param owner the value for CONTENT_TEMPLATE.OWNER
     *
     * @mbg.generated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.CREATE_DATETIME
     *
     * @return the value of CONTENT_TEMPLATE.CREATE_DATETIME
     *
     * @mbg.generated
     */
    public String getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.CREATE_DATETIME
     *
     * @param createDatetime the value for CONTENT_TEMPLATE.CREATE_DATETIME
     *
     * @mbg.generated
     */
    public void setCreateDatetime(String createDatetime) {
        this.createDatetime = createDatetime == null ? null : createDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.LAST_UPDATE_DATETIME
     *
     * @return the value of CONTENT_TEMPLATE.LAST_UPDATE_DATETIME
     *
     * @mbg.generated
     */
    public String getLastUpdateDatetime() {
        return lastUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.LAST_UPDATE_DATETIME
     *
     * @param lastUpdateDatetime the value for CONTENT_TEMPLATE.LAST_UPDATE_DATETIME
     *
     * @mbg.generated
     */
    public void setLastUpdateDatetime(String lastUpdateDatetime) {
        this.lastUpdateDatetime = lastUpdateDatetime == null ? null : lastUpdateDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.CUSTOM1
     *
     * @return the value of CONTENT_TEMPLATE.CUSTOM1
     *
     * @mbg.generated
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.CUSTOM1
     *
     * @param custom1 the value for CONTENT_TEMPLATE.CUSTOM1
     *
     * @mbg.generated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.CUSTOM2
     *
     * @return the value of CONTENT_TEMPLATE.CUSTOM2
     *
     * @mbg.generated
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.CUSTOM2
     *
     * @param custom2 the value for CONTENT_TEMPLATE.CUSTOM2
     *
     * @mbg.generated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.CUSTOM3
     *
     * @return the value of CONTENT_TEMPLATE.CUSTOM3
     *
     * @mbg.generated
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.CUSTOM3
     *
     * @param custom3 the value for CONTENT_TEMPLATE.CUSTOM3
     *
     * @mbg.generated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.CUSTOM4
     *
     * @return the value of CONTENT_TEMPLATE.CUSTOM4
     *
     * @mbg.generated
     */
    public Integer getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.CUSTOM4
     *
     * @param custom4 the value for CONTENT_TEMPLATE.CUSTOM4
     *
     * @mbg.generated
     */
    public void setCustom4(Integer custom4) {
        this.custom4 = custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.CUSTOM5
     *
     * @return the value of CONTENT_TEMPLATE.CUSTOM5
     *
     * @mbg.generated
     */
    public Integer getCustom5() {
        return custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.CUSTOM5
     *
     * @param custom5 the value for CONTENT_TEMPLATE.CUSTOM5
     *
     * @mbg.generated
     */
    public void setCustom5(Integer custom5) {
        this.custom5 = custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTENT_TEMPLATE.TEMPLATE
     *
     * @return the value of CONTENT_TEMPLATE.TEMPLATE
     *
     * @mbg.generated
     */
    public byte[] getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTENT_TEMPLATE.TEMPLATE
     *
     * @param template the value for CONTENT_TEMPLATE.TEMPLATE
     *
     * @mbg.generated
     */
    public void setTemplate(byte[] template) {
        this.template = template;
    }
}