package com.jwebcoder.emailsystem.entity;

public class EmailSendState {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.EMAIL_ID
     *
     * @mbg.generated
     */
    private String emailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.ERROR_DESCR
     *
     * @mbg.generated
     */
    private String errorDescr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.CREATE_DATETIME
     *
     * @mbg.generated
     */
    private String createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.LAST_UPDATE_DATETIME
     *
     * @mbg.generated
     */
    private String lastUpdateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.CUSTOM1
     *
     * @mbg.generated
     */
    private String custom1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.CUSTOM2
     *
     * @mbg.generated
     */
    private String custom2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.CUSTOM3
     *
     * @mbg.generated
     */
    private String custom3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.CUSTOM4
     *
     * @mbg.generated
     */
    private Integer custom4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMAIL_SEND_STATE.CUSTOM5
     *
     * @mbg.generated
     */
    private Integer custom5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.ID
     *
     * @return the value of EMAIL_SEND_STATE.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.ID
     *
     * @param id the value for EMAIL_SEND_STATE.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.VERSION
     *
     * @return the value of EMAIL_SEND_STATE.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.VERSION
     *
     * @param version the value for EMAIL_SEND_STATE.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.TYPE
     *
     * @return the value of EMAIL_SEND_STATE.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.TYPE
     *
     * @param type the value for EMAIL_SEND_STATE.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.EMAIL_ID
     *
     * @return the value of EMAIL_SEND_STATE.EMAIL_ID
     *
     * @mbg.generated
     */
    public String getEmailId() {
        return emailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.EMAIL_ID
     *
     * @param emailId the value for EMAIL_SEND_STATE.EMAIL_ID
     *
     * @mbg.generated
     */
    public void setEmailId(String emailId) {
        this.emailId = emailId == null ? null : emailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.STATUS
     *
     * @return the value of EMAIL_SEND_STATE.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.STATUS
     *
     * @param status the value for EMAIL_SEND_STATE.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.ERROR_DESCR
     *
     * @return the value of EMAIL_SEND_STATE.ERROR_DESCR
     *
     * @mbg.generated
     */
    public String getErrorDescr() {
        return errorDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.ERROR_DESCR
     *
     * @param errorDescr the value for EMAIL_SEND_STATE.ERROR_DESCR
     *
     * @mbg.generated
     */
    public void setErrorDescr(String errorDescr) {
        this.errorDescr = errorDescr == null ? null : errorDescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.CREATE_DATETIME
     *
     * @return the value of EMAIL_SEND_STATE.CREATE_DATETIME
     *
     * @mbg.generated
     */
    public String getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.CREATE_DATETIME
     *
     * @param createDatetime the value for EMAIL_SEND_STATE.CREATE_DATETIME
     *
     * @mbg.generated
     */
    public void setCreateDatetime(String createDatetime) {
        this.createDatetime = createDatetime == null ? null : createDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.LAST_UPDATE_DATETIME
     *
     * @return the value of EMAIL_SEND_STATE.LAST_UPDATE_DATETIME
     *
     * @mbg.generated
     */
    public String getLastUpdateDatetime() {
        return lastUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.LAST_UPDATE_DATETIME
     *
     * @param lastUpdateDatetime the value for EMAIL_SEND_STATE.LAST_UPDATE_DATETIME
     *
     * @mbg.generated
     */
    public void setLastUpdateDatetime(String lastUpdateDatetime) {
        this.lastUpdateDatetime = lastUpdateDatetime == null ? null : lastUpdateDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.CUSTOM1
     *
     * @return the value of EMAIL_SEND_STATE.CUSTOM1
     *
     * @mbg.generated
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.CUSTOM1
     *
     * @param custom1 the value for EMAIL_SEND_STATE.CUSTOM1
     *
     * @mbg.generated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.CUSTOM2
     *
     * @return the value of EMAIL_SEND_STATE.CUSTOM2
     *
     * @mbg.generated
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.CUSTOM2
     *
     * @param custom2 the value for EMAIL_SEND_STATE.CUSTOM2
     *
     * @mbg.generated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.CUSTOM3
     *
     * @return the value of EMAIL_SEND_STATE.CUSTOM3
     *
     * @mbg.generated
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.CUSTOM3
     *
     * @param custom3 the value for EMAIL_SEND_STATE.CUSTOM3
     *
     * @mbg.generated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.CUSTOM4
     *
     * @return the value of EMAIL_SEND_STATE.CUSTOM4
     *
     * @mbg.generated
     */
    public Integer getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.CUSTOM4
     *
     * @param custom4 the value for EMAIL_SEND_STATE.CUSTOM4
     *
     * @mbg.generated
     */
    public void setCustom4(Integer custom4) {
        this.custom4 = custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMAIL_SEND_STATE.CUSTOM5
     *
     * @return the value of EMAIL_SEND_STATE.CUSTOM5
     *
     * @mbg.generated
     */
    public Integer getCustom5() {
        return custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMAIL_SEND_STATE.CUSTOM5
     *
     * @param custom5 the value for EMAIL_SEND_STATE.CUSTOM5
     *
     * @mbg.generated
     */
    public void setCustom5(Integer custom5) {
        this.custom5 = custom5;
    }
}