package com.jwebcoder.emailsystem.dao;

import com.jwebcoder.emailsystem.entity.Attachment;

public interface AttachmentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbg.generated
     */
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbg.generated
     */
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbg.generated
     */
    Attachment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Attachment record);
}