package com.jwebcoder.emailsystem.dao;

import com.jwebcoder.emailsystem.entity.EmailSendState;
import org.springframework.stereotype.Repository;

@Repository
public interface EmailSendStateDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMAIL_SEND_STATE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMAIL_SEND_STATE
     *
     * @mbg.generated
     */
    int insert(EmailSendState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMAIL_SEND_STATE
     *
     * @mbg.generated
     */
    int insertSelective(EmailSendState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMAIL_SEND_STATE
     *
     * @mbg.generated
     */
    EmailSendState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMAIL_SEND_STATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmailSendState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMAIL_SEND_STATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmailSendState record);
}