package com.jwebcoder.emailsystem.dao;

import com.jwebcoder.emailsystem.entity.SimpleEmail;
import org.springframework.stereotype.Repository;

@Repository
public interface SimpleEmailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMPLE_EMAIL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMPLE_EMAIL
     *
     * @mbg.generated
     */
    int insert(SimpleEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMPLE_EMAIL
     *
     * @mbg.generated
     */
    int insertSelective(SimpleEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMPLE_EMAIL
     *
     * @mbg.generated
     */
    SimpleEmail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMPLE_EMAIL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SimpleEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMPLE_EMAIL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimpleEmail record);
}